# Generated by Django 4.2 on 2023-05-13 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Autotesting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(max_length=10, verbose_name='Тип данных для тестов')),
            ],
        ),
        migrations.RemoveField(
            model_name='laboratory_works',
            name='max_points',
        ),
        migrations.RemoveField(
            model_name='laboratory_works',
            name='num_of_tasks',
        ),
        migrations.RemoveField(
            model_name='laboratory_works',
            name='points_for_task',
        ),
        migrations.AddField(
            model_name='tasks',
            name='points',
            field=models.IntegerField(default=0, verbose_name='Кол-во баллов за задание'),
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(verbose_name='Данные для тестов')),
                ('test_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Autotesting.test_type')),
            ],
        ),
        migrations.AddField(
            model_name='test_type',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Autotesting.tasks'),
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0, verbose_name='Суммарное количество баллов студента')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Autotesting.students')),
            ],
        ),
        migrations.CreateModel(
            name='Attempts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_attempt', models.DateTimeField(verbose_name='Дата попытки')),
                ('text_of_attempt', models.TextField(verbose_name='Отчет о попытке')),
                ('comment', models.TextField(verbose_name='Комментарий преподавателя')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Autotesting.students')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Autotesting.tasks')),
            ],
        ),
    ]
