# Generated by Django 4.0.4 on 2023-06-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autotesting', '0003_remove_test_type_task_tests_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tests',
            name='task',
        ),
        migrations.RemoveField(
            model_name='tests',
            name='test_type',
        ),
        migrations.RenameField(
            model_name='laboratory_works',
            old_name='topic',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='students',
            name='name',
        ),
        migrations.AddField(
            model_name='students',
            name='login',
            field=models.CharField(max_length=150, null=True, verbose_name='Логин студента'),
        ),
        migrations.AddField(
            model_name='students',
            name='yandex_id',
            field=models.IntegerField(null=True, verbose_name='ID Яндекса'),
        ),
        migrations.DeleteModel(
            name='Test_type',
        ),
        migrations.DeleteModel(
            name='Tests',
        ),
    ]
