# Generated by Django 4.0.4 on 2023-06-11 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autotesting', '0005_remove_students_yandex_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='lab_work',
        ),
        migrations.RemoveField(
            model_name='tasksvariants',
            name='task',
        ),
        migrations.RemoveField(
            model_name='tasksvariants',
            name='variant',
        ),
        migrations.RemoveField(
            model_name='students',
            name='variant',
        ),
        migrations.AddField(
            model_name='laboratory_works',
            name='contest_id',
            field=models.IntegerField(null=True, verbose_name='Идентификатор контеста/лабы'),
        ),
        migrations.DeleteModel(
            name='Attempts',
        ),
        migrations.DeleteModel(
            name='Tasks',
        ),
        migrations.DeleteModel(
            name='TasksVariants',
        ),
        migrations.DeleteModel(
            name='Variants',
        ),
    ]
