# Generated by Django 4.0.4 on 2023-06-12 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Autotesting', '0006_remove_tasks_lab_work_remove_tasksvariants_task_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_problem_id', models.CharField(max_length=50, verbose_name='ID задачи в контесте')),
                ('name', models.CharField(max_length=150, verbose_name='Назание задачи')),
                ('text', models.TextField(verbose_name='Текст задачи')),
                ('input_data', models.TextField(verbose_name='Что на входе')),
                ('output_data', models.TextField(verbose_name='Что на выходе')),
                ('points', models.IntegerField(default=0, verbose_name='Кол-во баллов за задание')),
                ('lab_work', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Autotesting.laboratory_works')),
            ],
        ),
    ]
