# Generated by Django 4.0.4 on 2023-06-12 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Autotesting', '0007_tasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.IntegerField(verbose_name='Номер варианта')),
            ],
        ),
        migrations.CreateModel(
            name='TasksVariants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Autotesting.tasks')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Autotesting.variants')),
            ],
        ),
        migrations.AddField(
            model_name='students',
            name='variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Autotesting.variants'),
        ),
    ]
