# Generated by Django 4.2 on 2023-06-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autotesting', '0008_variants_tasksvariants_students_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='points',
            field=models.IntegerField(default=0, verbose_name='Общее количество баллов студента'),
        ),
        migrations.DeleteModel(
            name='Journal',
        ),
    ]
