# Generated by Django 4.2 on 2023-06-20 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Autotesting', '0009_students_points_delete_journal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solutions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createAt', models.DateTimeField(verbose_name='Дата отправки решения')),
                ('status', models.CharField(max_length=100, verbose_name='Статус решения')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Autotesting.students')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Autotesting.tasks')),
            ],
        ),
    ]
